
#
# Compile and run MOSEK examples
#
CSC=mcs
acc1.exe: acc1.cs
	$(CSC) -debug -out:acc1.exe -r:../../platform/linuxaarch64/bin/mosekdotnet10_0.dll -target:exe acc1.cs

acc2.exe: acc2.cs
	$(CSC) -debug -out:acc2.exe -r:../../platform/linuxaarch64/bin/mosekdotnet10_0.dll -target:exe acc2.cs

blas_lapack.exe: blas_lapack.cs
	$(CSC) -debug -out:blas_lapack.exe -r:../../platform/linuxaarch64/bin/mosekdotnet10_0.dll -target:exe blas_lapack.cs

callback.exe: callback.cs
	$(CSC) -debug -out:callback.exe -r:../../platform/linuxaarch64/bin/mosekdotnet10_0.dll -target:exe callback.cs

portfolio_1_basic.exe: portfolio_1_basic.cs
	$(CSC) -debug -out:portfolio_1_basic.exe -r:../../platform/linuxaarch64/bin/mosekdotnet10_0.dll -target:exe portfolio_1_basic.cs

portfolio_2_frontier.exe: portfolio_2_frontier.cs
	$(CSC) -debug -out:portfolio_2_frontier.exe -r:../../platform/linuxaarch64/bin/mosekdotnet10_0.dll -target:exe portfolio_2_frontier.cs

portfolio_3_impact.exe: portfolio_3_impact.cs
	$(CSC) -debug -out:portfolio_3_impact.exe -r:../../platform/linuxaarch64/bin/mosekdotnet10_0.dll -target:exe portfolio_3_impact.cs

portfolio_4_transcost.exe: portfolio_4_transcost.cs
	$(CSC) -debug -out:portfolio_4_transcost.exe -r:../../platform/linuxaarch64/bin/mosekdotnet10_0.dll -target:exe portfolio_4_transcost.cs

portfolio_5_card.exe: portfolio_5_card.cs
	$(CSC) -debug -out:portfolio_5_card.exe -r:../../platform/linuxaarch64/bin/mosekdotnet10_0.dll -target:exe portfolio_5_card.cs

portfolio_6_factor.exe: portfolio_6_factor.cs
	$(CSC) -debug -out:portfolio_6_factor.exe -r:../../platform/linuxaarch64/bin/mosekdotnet10_0.dll -target:exe portfolio_6_factor.cs

cqo1.exe: cqo1.cs
	$(CSC) -debug -out:cqo1.exe -r:../../platform/linuxaarch64/bin/mosekdotnet10_0.dll -target:exe cqo1.cs

ceo1.exe: ceo1.cs
	$(CSC) -debug -out:ceo1.exe -r:../../platform/linuxaarch64/bin/mosekdotnet10_0.dll -target:exe ceo1.cs

pow1.exe: pow1.cs
	$(CSC) -debug -out:pow1.exe -r:../../platform/linuxaarch64/bin/mosekdotnet10_0.dll -target:exe pow1.cs

djc1.exe: djc1.cs
	$(CSC) -debug -out:djc1.exe -r:../../platform/linuxaarch64/bin/mosekdotnet10_0.dll -target:exe djc1.cs

concurrent1.exe: concurrent1.cs
	$(CSC) -debug -out:concurrent1.exe -r:../../platform/linuxaarch64/bin/mosekdotnet10_0.dll -target:exe concurrent1.cs

feasrepairex1.exe: feasrepairex1.cs
	$(CSC) -debug -out:feasrepairex1.exe -r:../../platform/linuxaarch64/bin/mosekdotnet10_0.dll -target:exe feasrepairex1.cs

helloworld.exe: helloworld.cs
	$(CSC) -debug -out:helloworld.exe -r:../../platform/linuxaarch64/bin/mosekdotnet10_0.dll -target:exe helloworld.cs

lo1.exe: lo1.cs
	$(CSC) -debug -out:lo1.exe -r:../../platform/linuxaarch64/bin/mosekdotnet10_0.dll -target:exe lo1.cs

lo2.exe: lo2.cs
	$(CSC) -debug -out:lo2.exe -r:../../platform/linuxaarch64/bin/mosekdotnet10_0.dll -target:exe lo2.cs

logistic.exe: logistic.cs
	$(CSC) -debug -out:logistic.exe -r:../../platform/linuxaarch64/bin/mosekdotnet10_0.dll -target:exe logistic.cs

gp1.exe: gp1.cs
	$(CSC) -debug -out:gp1.exe -r:../../platform/linuxaarch64/bin/mosekdotnet10_0.dll -target:exe gp1.cs

milo1.exe: milo1.cs
	$(CSC) -debug -out:milo1.exe -r:../../platform/linuxaarch64/bin/mosekdotnet10_0.dll -target:exe milo1.cs

mioinitsol.exe: mioinitsol.cs
	$(CSC) -debug -out:mioinitsol.exe -r:../../platform/linuxaarch64/bin/mosekdotnet10_0.dll -target:exe mioinitsol.cs

mico1.exe: mico1.cs
	$(CSC) -debug -out:mico1.exe -r:../../platform/linuxaarch64/bin/mosekdotnet10_0.dll -target:exe mico1.cs

opt_server_async.exe: opt_server_async.cs
	$(CSC) -debug -out:opt_server_async.exe -r:../../platform/linuxaarch64/bin/mosekdotnet10_0.dll -target:exe opt_server_async.cs

opt_server_sync.exe: opt_server_sync.cs
	$(CSC) -debug -out:opt_server_sync.exe -r:../../platform/linuxaarch64/bin/mosekdotnet10_0.dll -target:exe opt_server_sync.cs

parallel.exe: parallel.cs
	$(CSC) -debug -out:parallel.exe -r:../../platform/linuxaarch64/bin/mosekdotnet10_0.dll -target:exe parallel.cs

parameters.exe: parameters.cs
	$(CSC) -debug -out:parameters.exe -r:../../platform/linuxaarch64/bin/mosekdotnet10_0.dll -target:exe parameters.cs

pinfeas.exe: pinfeas.cs
	$(CSC) -debug -out:pinfeas.exe -r:../../platform/linuxaarch64/bin/mosekdotnet10_0.dll -target:exe pinfeas.cs

reoptimization.exe: reoptimization.cs
	$(CSC) -debug -out:reoptimization.exe -r:../../platform/linuxaarch64/bin/mosekdotnet10_0.dll -target:exe reoptimization.cs

qcqo1.exe: qcqo1.cs
	$(CSC) -debug -out:qcqo1.exe -r:../../platform/linuxaarch64/bin/mosekdotnet10_0.dll -target:exe qcqo1.cs

qo1.exe: qo1.cs
	$(CSC) -debug -out:qo1.exe -r:../../platform/linuxaarch64/bin/mosekdotnet10_0.dll -target:exe qo1.cs

response.exe: response.cs
	$(CSC) -debug -out:response.exe -r:../../platform/linuxaarch64/bin/mosekdotnet10_0.dll -target:exe response.cs

sdo1.exe: sdo1.cs
	$(CSC) -debug -out:sdo1.exe -r:../../platform/linuxaarch64/bin/mosekdotnet10_0.dll -target:exe sdo1.cs

sdo2.exe: sdo2.cs
	$(CSC) -debug -out:sdo2.exe -r:../../platform/linuxaarch64/bin/mosekdotnet10_0.dll -target:exe sdo2.cs

sdo_lmi.exe: sdo_lmi.cs
	$(CSC) -debug -out:sdo_lmi.exe -r:../../platform/linuxaarch64/bin/mosekdotnet10_0.dll -target:exe sdo_lmi.cs

sensitivity.exe: sensitivity.cs
	$(CSC) -debug -out:sensitivity.exe -r:../../platform/linuxaarch64/bin/mosekdotnet10_0.dll -target:exe sensitivity.cs

simple.exe: simple.cs
	$(CSC) -debug -out:simple.exe -r:../../platform/linuxaarch64/bin/mosekdotnet10_0.dll -target:exe simple.cs

solutionquality.exe: solutionquality.cs
	$(CSC) -debug -out:solutionquality.exe -r:../../platform/linuxaarch64/bin/mosekdotnet10_0.dll -target:exe solutionquality.cs

solvebasis.exe: solvebasis.cs
	$(CSC) -debug -out:solvebasis.exe -r:../../platform/linuxaarch64/bin/mosekdotnet10_0.dll -target:exe solvebasis.cs

solvelinear.exe: solvelinear.cs
	$(CSC) -debug -out:solvelinear.exe -r:../../platform/linuxaarch64/bin/mosekdotnet10_0.dll -target:exe solvelinear.cs

sparsecholesky.exe: sparsecholesky.cs
	$(CSC) -debug -out:sparsecholesky.exe -r:../../platform/linuxaarch64/bin/mosekdotnet10_0.dll -target:exe sparsecholesky.cs

all: acc1.exe acc2.exe blas_lapack.exe callback.exe portfolio_1_basic.exe portfolio_2_frontier.exe portfolio_3_impact.exe portfolio_4_transcost.exe portfolio_5_card.exe portfolio_6_factor.exe cqo1.exe ceo1.exe pow1.exe djc1.exe concurrent1.exe feasrepairex1.exe helloworld.exe lo1.exe lo2.exe logistic.exe gp1.exe milo1.exe mioinitsol.exe mico1.exe opt_server_async.exe opt_server_sync.exe parallel.exe parameters.exe pinfeas.exe reoptimization.exe qcqo1.exe qo1.exe response.exe sdo1.exe sdo2.exe sdo_lmi.exe sensitivity.exe simple.exe solutionquality.exe solvebasis.exe solvelinear.exe sparsecholesky.exe

clean:
	rm -f acc1.exe acc2.exe blas_lapack.exe callback.exe portfolio_1_basic.exe portfolio_2_frontier.exe portfolio_3_impact.exe portfolio_4_transcost.exe portfolio_5_card.exe portfolio_6_factor.exe cqo1.exe ceo1.exe pow1.exe djc1.exe concurrent1.exe feasrepairex1.exe helloworld.exe lo1.exe lo2.exe logistic.exe gp1.exe milo1.exe mioinitsol.exe mico1.exe opt_server_async.exe opt_server_sync.exe parallel.exe parameters.exe pinfeas.exe reoptimization.exe qcqo1.exe qo1.exe response.exe sdo1.exe sdo2.exe sdo_lmi.exe sensitivity.exe simple.exe solutionquality.exe solvebasis.exe solvelinear.exe sparsecholesky.exe

test: acc1.exe acc2.exe blas_lapack.exe callback.exe portfolio_1_basic.exe portfolio_2_frontier.exe portfolio_3_impact.exe portfolio_4_transcost.exe portfolio_5_card.exe portfolio_6_factor.exe cqo1.exe ceo1.exe pow1.exe djc1.exe concurrent1.exe feasrepairex1.exe helloworld.exe lo1.exe lo2.exe logistic.exe gp1.exe milo1.exe mioinitsol.exe mico1.exe opt_server_async.exe opt_server_sync.exe parallel.exe parameters.exe pinfeas.exe reoptimization.exe qcqo1.exe qo1.exe response.exe sdo1.exe sdo2.exe sdo_lmi.exe sensitivity.exe simple.exe solutionquality.exe solvebasis.exe solvelinear.exe sparsecholesky.exe
	cp ../../platform/linuxaarch64/bin/mosekdotnet10_0.dll .
	LD_LIBRARY_PATH=../../platform/linuxaarch64/bin mono acc1.exe
	LD_LIBRARY_PATH=../../platform/linuxaarch64/bin mono acc2.exe
	LD_LIBRARY_PATH=../../platform/linuxaarch64/bin mono blas_lapack.exe
	LD_LIBRARY_PATH=../../platform/linuxaarch64/bin mono callback.exe
	LD_LIBRARY_PATH=../../platform/linuxaarch64/bin mono portfolio_1_basic.exe
	LD_LIBRARY_PATH=../../platform/linuxaarch64/bin mono portfolio_2_frontier.exe
	LD_LIBRARY_PATH=../../platform/linuxaarch64/bin mono portfolio_3_impact.exe
	LD_LIBRARY_PATH=../../platform/linuxaarch64/bin mono portfolio_4_transcost.exe
	LD_LIBRARY_PATH=../../platform/linuxaarch64/bin mono portfolio_5_card.exe
	LD_LIBRARY_PATH=../../platform/linuxaarch64/bin mono portfolio_6_factor.exe
	LD_LIBRARY_PATH=../../platform/linuxaarch64/bin mono cqo1.exe
	LD_LIBRARY_PATH=../../platform/linuxaarch64/bin mono ceo1.exe
	LD_LIBRARY_PATH=../../platform/linuxaarch64/bin mono pow1.exe
	LD_LIBRARY_PATH=../../platform/linuxaarch64/bin mono djc1.exe
	LD_LIBRARY_PATH=../../platform/linuxaarch64/bin mono concurrent1.exe
	LD_LIBRARY_PATH=../../platform/linuxaarch64/bin mono feasrepairex1.exe
	LD_LIBRARY_PATH=../../platform/linuxaarch64/bin mono helloworld.exe
	LD_LIBRARY_PATH=../../platform/linuxaarch64/bin mono lo1.exe
	LD_LIBRARY_PATH=../../platform/linuxaarch64/bin mono lo2.exe
	LD_LIBRARY_PATH=../../platform/linuxaarch64/bin mono logistic.exe
	LD_LIBRARY_PATH=../../platform/linuxaarch64/bin mono gp1.exe
	LD_LIBRARY_PATH=../../platform/linuxaarch64/bin mono milo1.exe
	LD_LIBRARY_PATH=../../platform/linuxaarch64/bin mono mioinitsol.exe
	LD_LIBRARY_PATH=../../platform/linuxaarch64/bin mono mico1.exe
	LD_LIBRARY_PATH=../../platform/linuxaarch64/bin mono opt_server_async.exe
	LD_LIBRARY_PATH=../../platform/linuxaarch64/bin mono opt_server_sync.exe
	LD_LIBRARY_PATH=../../platform/linuxaarch64/bin mono parallel.exe
	LD_LIBRARY_PATH=../../platform/linuxaarch64/bin mono parameters.exe
	LD_LIBRARY_PATH=../../platform/linuxaarch64/bin mono pinfeas.exe
	LD_LIBRARY_PATH=../../platform/linuxaarch64/bin mono reoptimization.exe
	LD_LIBRARY_PATH=../../platform/linuxaarch64/bin mono qcqo1.exe
	LD_LIBRARY_PATH=../../platform/linuxaarch64/bin mono qo1.exe
	LD_LIBRARY_PATH=../../platform/linuxaarch64/bin mono response.exe
	LD_LIBRARY_PATH=../../platform/linuxaarch64/bin mono sdo1.exe
	LD_LIBRARY_PATH=../../platform/linuxaarch64/bin mono sdo2.exe
	LD_LIBRARY_PATH=../../platform/linuxaarch64/bin mono sdo_lmi.exe
	LD_LIBRARY_PATH=../../platform/linuxaarch64/bin mono sensitivity.exe
	LD_LIBRARY_PATH=../../platform/linuxaarch64/bin mono simple.exe
	LD_LIBRARY_PATH=../../platform/linuxaarch64/bin mono solutionquality.exe
	LD_LIBRARY_PATH=../../platform/linuxaarch64/bin mono solvebasis.exe
	LD_LIBRARY_PATH=../../platform/linuxaarch64/bin mono solvelinear.exe
	LD_LIBRARY_PATH=../../platform/linuxaarch64/bin mono sparsecholesky.exe
